export const keywords = [
    "garden",
    "gardening",
    "flowers",
    "greenhouse",
    "plants",
    "vegetables",
    "fruit",
    "trees",
    "landscaping",
    "gardens",
    "lawn",
    "soil",
    "compost",
    "mulch",
    "fertilizer",
    "garden pests",
    "weeds",
    "plant disease",
    "plant pruning",
    "plant propagation",
    "gardening tools",
    "gardening equipment",
    "watering",
    "Weed control",
    "Gardening tips",
    "Garden life hacks",
    "Garden tutorials",
    "Repotting plants",
    "Taking plant cuttings",
    "Garden care",
    "Garden ideas",
    "Garden projects",
    "DIY garden",
    "Pruning roses",
    "Creating raised beds",
    "Herb garden",
    "Harvesting herbs",
    "Orchard",
    "Planting fruit trees",
    "Planting berries",
    "Winter-hardy plants",
    "Low-maintenance plants",
    "Natural garden",
    "Mowing the lawn",
    "Seeding the lawn",
    "Laying sod",
    "Fertilizing the lawn",
    "Gardening for beginners",
    "Vertical garden",
    "Planting a balcony garden",
    "Creating a garden pond",
    "Pond maintenance",
    "Creating a lawn",
    "Pruning trees",
    "Pruning shrubs",
    "Child-friendly garden",
    "Building a birdhouse",
    "Insect hotel",
    "Wildlife in the garden",
    "Frost protection in the garden",
    "Summer flowers",
    "Spring flowers",
    "Garden furniture",
    "Garden lighting",
    "Garden decoration",
    "Taking cuttings",
] as const